version: "3.9"

networks:
  careerlink-network:
    driver: bridge

services:

  api-gateway:
    build: ./backend/api-gateway
    container_name: api-gateway
    restart: always
    env_file:
      - ./backend/api-gateway/.env.production
    depends_on:
      - user-service
      - admin-service
      - company-service
      - notification-service
      - job-service
      - resume-service
      - post-service
      - subscription-service
      - chat-service
      - report-service
      - frontend
    ports:
      - "127.0.0.1:5000:5000"
    networks:
      - careerlink-network

  user-service:
    build: ./backend/user-service
    container_name: user-service
    restart: always
    env_file:
      - ./backend/user-service/.env.production
    ports:
      - "127.0.0.1:5001:5001"
    networks:
      - careerlink-network

  admin-service:
    build: ./backend/admin-service
    container_name: admin-service
    restart: always
    env_file:
      - ./backend/admin-service/.env.production
    networks:
      - careerlink-network

  company-service:
    build: ./backend/company-service
    container_name: company-service
    restart: always
    env_file:
      - ./backend/company-service/.env.production
    networks:
      - careerlink-network

  notification-service:
    build: ./backend/notification-service
    container_name: notification-service
    restart: always
    env_file:
      - ./backend/notification-service/.env.production
    ports:
      - "127.0.0.1:5004:5004"
    networks:
      - careerlink-network

  job-service:
    build: ./backend/job-service
    container_name: job-service
    restart: always
    env_file:
      - ./backend/job-service/.env.production
    networks:
      - careerlink-network

  resume-service:
    build: ./backend/resume-service
    container_name: resume-service
    restart: always
    env_file:
      - ./backend/resume-service/.env.production
    networks:
      - careerlink-network

  post-service:
    build: ./backend/post-service
    container_name: post-service
    restart: always
    env_file:
      - ./backend/post-service/.env.production
    networks:
      - careerlink-network

  subscription-service:
    build: ./backend/subscription-service
    container_name: subscription-service
    restart: always
    env_file:
      - ./backend/subscription-service/.env.production
    networks:
      - careerlink-network

  chat-service:
    build: ./backend/chat-service
    container_name: chat-service
    restart: always
    env_file:
      - ./backend/chat-service/.env.production
    networks:
      - careerlink-network

  report-service:
    build: ./backend/report-service
    container_name: report-service
    restart: always
    env_file:
      - ./backend/report-service/.env.production
    networks:
      - careerlink-network

  # ===================== FRONTEND =====================

  frontend:
    build: ./frontend
    container_name: frontend
    environment:
      - JWT_SECRET=careerlinkJWT
      - API_GATEWAY_ROUTE=https://careerlink.space/api
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - careerlink-network


