import { Container } from "inversify";
import { TYPES } from "./types";
import { UserRepository } from "./infrastructure/repositories/UserRepository";
import { UserDetailsRepository } from "./infrastructure/repositories/UserDetailsRepository";
import { LoginUser } from "./application/use-cases/LoginUser";
import { SignupUser } from "./application/use-cases/SignupUser";
import { AddUserDetails } from "./application/use-cases/AddUserDetails";
import { AlterUserStatus } from "./application/use-cases/AlterUserStatus";
import { ChangePass } from "./application/use-cases/ChangePass";
import { CheckUserBlock } from "./application/use-cases/CheckUserBlock";
import { EditUserDetails } from "./application/use-cases/EditUserDetails";
import { GetUserDetails } from "./application/use-cases/GetUserDetails"; 
import { GetAllUsers } from "./application/use-cases/GetUsers";
import { GoogleLogin } from "./application/use-cases/GoogleLogin";
import { UserController } from "./interfaces/controllers/UserController";
import { UserDetailsController } from "./interfaces/controllers/UserDetailsController";
import { SendOTP } from "./application/use-cases/SignupUser";
import { SendResetOTP } from "./application/use-cases/ChangePass";
import { Mailer } from "./utils/MailHelper";
import { VerifyOTP } from "./application/use-cases/VerifyOTP";
import { GetUserNames } from "./application/use-cases/GetUserNames";
import { GetGithubDetails } from "./application/use-cases/GetGithubDetails";
import { GetConnections } from "./application/use-cases/GetConnections";
import { ConnectionsRepository } from "./infrastructure/repositories/ConnectionsRepository";
import { ConnectionController } from "./interfaces/controllers/ConnectionController";
import { AlterConnectionRequest } from "./application/use-cases/AlterConnectionRequest";
import { GetUserRequests } from "./application/use-cases/GetUserRequests";
import { EvaluateRequest } from "./application/use-cases/EvaluateRequest";
import { GetConnectedUsers } from "./application/use-cases/GetConnectedUsers";
import { RemoveConnection } from "./application/use-cases/RemoveConnection";
import { GetConnectionDetails } from "./application/use-cases/GetConnectionDetails";

const container = new Container();

container.bind(TYPES.IUserRepository).to(UserRepository).inSingletonScope();
container.bind(TYPES.IUserDetailsRepository).to(UserDetailsRepository).inSingletonScope();
container.bind(TYPES.IConnectionRepository).to(ConnectionsRepository).inSingletonScope();

container.bind(TYPES.ILoginUser).to(LoginUser).inSingletonScope();
container.bind(TYPES.ISignupUser).to(SignupUser).inSingletonScope();
container.bind(TYPES.IAddUserDetails).to(AddUserDetails).inSingletonScope();
container.bind(TYPES.IAlterUserStatus).to(AlterUserStatus).inSingletonScope();
container.bind(TYPES.IChangePass).to(ChangePass).inSingletonScope();
container.bind(TYPES.ICheckUserBlock).to(CheckUserBlock).inSingletonScope();
container.bind(TYPES.IEditUserDetails).to(EditUserDetails).inSingletonScope();
container.bind(TYPES.IGetUserDetails).to(GetUserDetails).inSingletonScope();
container.bind(TYPES.IGetAllUsers).to(GetAllUsers).inSingletonScope();
container.bind(TYPES.IGoogleLogin).to(GoogleLogin).inSingletonScope();
container.bind(TYPES.ISendOTP).to(SendOTP).inSingletonScope();
container.bind(TYPES.ISendResetOtp).to(SendResetOTP).inSingletonScope();
container.bind(TYPES.Mailer).to(Mailer).inSingletonScope(); 
container.bind(TYPES.IVerifyOTP).to(VerifyOTP).inSingletonScope();
container.bind(TYPES.IGetUserNames).to(GetUserNames).inSingletonScope();
container.bind(TYPES.IGetGithubDetails).to(GetGithubDetails).inSingletonScope();
container.bind(TYPES.IGetConnections).to(GetConnections).inSingletonScope();
container.bind(TYPES.IAlterConnectionRequest).to(AlterConnectionRequest).inSingletonScope();
container.bind(TYPES.IGetUserRequests).to(GetUserRequests).inSingletonScope();
container.bind(TYPES.IEvaluateRequest).to(EvaluateRequest).inSingletonScope();
container.bind(TYPES.IGetConnectedUsers).to(GetConnectedUsers).inSingletonScope();
container.bind(TYPES.IRemoveConnection).to(RemoveConnection).inSingletonScope();
container.bind(TYPES.IGetConnectionDetails).to(GetConnectionDetails).inSingletonScope();

container.bind<UserController>(TYPES.UserController).to(UserController);
container.bind<UserDetailsController>(TYPES.UserDetailsController).to(UserDetailsController);
container.bind<ConnectionController>(TYPES.ConnectionController).to(ConnectionController);

export default container; 